Make navbar icons links
rubyforgood/voices-of-consent pull request #414
Opened 2020-02-14 12:28 UTC by sarslanoglu

Resolves #159 

### Description

Navbar icons where pointing only status. Right now all of them is using filters and current_user_id if possible

### Type of change

Links of navbar items are changed
Additional check is added to box_request controller for user_id existence

### How Has This Been Tested?

Tested manually

2020-02-14 19:57 UTC, h-m-m commented on app/models/box_request.rb
> +  scope :designed, ->(){ joins(:box).where("boxes.aasm_state = ?", "designed") }
Nice typo catch!

2020-02-18 19:16 UTC, maebeale reviewed
@sarslanoglu thank you!!! 

this task gets at some core usability, so thank you for digging in to where the links should point. 

i don't think we want to filter all of these on current_user bc then an admin wouldn't be able to see the work of everyone. 

ideally people with the respective permission will see either unclaimed items or items they've claimed but not completed, unless they're a superadmin and can see everything. (i think the closest to this we're getting currently is if they have Permission::MANAGE_USERS).

do you have suggestions for how to move forward? (e.g. should we approve of this PR and add a new issue, or do you feel comfortable updating what's here to get a little closer?)

2020-02-22 19:03 UTC, oconnelc commented
I'm not sure if anyone else has seen this, but I pulled this branch into my work space and it was working  great, until I completely restarted all of the processes (the docker-compose, the rails server and web pack). I found that I was unable to login. The code correctly identified the state as not being logged in, but when I tried to go the root page (http://localhost:3000), I got the following error:

![image](https://user-images.githubusercontent.com/1112973/75097713-e6d0bf80-557b-11ea-9423-7e5228632783.png)

It looks like the current user isn't getting set. It's possible that my local work space wasn't in a good state and the problem has nothing to do with this pull request.

2020-02-24 15:17 UTC, sarslanoglu commented
@oconnelc It was my mistake to not support not logged in users at first place. It should be fixed by second [commit](https://github.com/rubyforgood/voices-of-consent/pull/414/commits/1d2f9e307a221a9b9c6c714c29307c8bb2fd3069)

@maebeale I changed it to support both not signed in users also add support for admin users. Basically admins can open with current_user_id to see everything

2020-02-26 21:25 UTC, h-m-m commented
@sarslanoglu Do you think we should add a test for each of the non-logged in, logged in without admin, and logged in as admin behavior? I'm thinking a test to make sure the request works end-to-end would be enough, as that would work as a regression test for what @oconnelc found

2020-02-26 22:04 UTC, maebeale commented
Totally, @h-m-m !

2020-03-01 15:31 UTC, sarslanoglu commented
@maebeale @h-m-m Last commit is dealing with navbar tests

2020-03-10 01:16 UTC, maebeale commented on app/controllers/box_requests_controller.rb
> +      @box_requests.where(reviewed_by_id: params[:current_user_id]) if params[:current_user_id].present?
@sarslanoglu should this be `@box_requests = @box_requests.where...` ?

2020-03-10 01:16 UTC, maebeale requested changes
@sarslanoglu thank you for this PR! 
i merged in some other navbar PR's, which created a merge issue.

2020-03-19 01:36 UTC, merged